module.exports = {
  TechnologySidebar: {
    'About the ZKVM': [{type: 'autogenerated', dirName: 'explainers/zkvm'}],
    'About the Proof System': [
      {type: 'autogenerated', dirName: 'explainers/proof-system'}, 
      {type: 'link',
      label: 'ZKP Whitepaper',
      href: 'https://www.risczero.com/proof-system-in-detail.pdf',},
    ],
    'Reference Docs': [{type: 'autogenerated', dirName: 'reference-docs'},],
  },
  BuildSidebar: {
    
  },

  GettingStartedSidebar: [
    { type: 'category',
      label: '"Hello, Multiply!"',
      items: [
        {
          type: 'doc',
          label: '"Hello, Multiply!" Tutorial',
          id: 'examples/hello_multiply',
        },
        {
          type: 'doc',
          label: 'Understanding "Hello, Multiply!"',
          id: 'examples/understanding-hello-multiply',
        },
        {
          type: 'link',
          label: '"Hello, Multiply!" Source',
          href: 'https://github.com/risc0/risc0/tree/main/examples/factors',
        },
      ]
    },
    { type: 'category',
      label: 'RISC Zero Starter Template',
      items: [
        {
          type: 'doc',
          label: 'Understanding the Starter Template',
          id: 'examples/understanding_template',
        },
        {
          type: 'link',
          label: 'Starter Template via `cargo risczero new`',
          href: 'https://crates.io/crates/cargo-risczero',
        }
      ]
    },
    { type: 'category',
    label: 'Password Validity Checker',
    items: [
      {
        type: 'doc',
        label: 'Understanding the Password Validity Checker',
        id: 'examples/password_checker',
      },
      {
        type: 'link',
        label: 'Password Validity Checker Source',
        href: 'https://github.com/risc0/risc0/tree/main/examples/password-checker',
      }
    ]
  },
    {
      type: 'doc',
      label: 'FAQ',
      id: 'tech_faq',
    },
    { 
      type: 'link',
      label: 'ZK Hack III Workshop',
      href: 'https://youtu.be/wECQcmk-5ss',
    },
    { type: 'link',
      label: 'Reference Documentation',
      href: 'https://docs.rs/risc0-zkvm/latest/risc0_zkvm/',
    },
    { type: 'link',
      label: 'Contribute to RISC Zero',
      href: 'https://github.com/risc0/risc0',
    }, 

  ]
};
